/*
 * SPDX-FileCopyrightText: (C) 2022 Matthias Fehring <https://www.huessenbergnetz.de>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#ifndef MELDARI_LOGGING_H
#define MELDARI_LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(MEL_CORE)
Q_DECLARE_LOGGING_CATEGORY(MEL_CONF)
Q_DECLARE_LOGGING_CATEGORY(MEL_AUTHN)
Q_DECLARE_LOGGING_CATEGORY(MEL_AUTHZ)
Q_DECLARE_LOGGING_CATEGORY(MEL_CUTELEE)

#endif // MELDARI_LOGGING_H
